### PR TITLE
add number slider input type

### PR DESCRIPTION
**Pull request by bgstack15**
No protections are provided for a user entering whatever he wants in the box on the form.
Javascript is required on the form to get the slider to update the text field.

### CODE REVIEW

**Comment by bgstack15** [comment]
Now that I think about it, I think the javascript could be removed and the raw number from the slider could be passed to the POST form, but in my browser the slider doesn't show the value. I had to add the text box so I could see the numerical value it would send.

**Comment by div72** [comment]
> Now that I think about it, I think the javascript could be removed and the raw number from the slider could be passed to the POST form, but in my browser the slider doesn't show the value. I had to add the text box so I could see the numerical value it would send.

Wouldn't using the range type be better precisely for this reason?

**Comment by bgstack15** [comment]
I didn't know about that element. Would you like me to rewrite this PR with that element? But also, this PR did not include any server-side logic to bound the inputs to the schema min-max. So as written, anybody could POST whatever they want anyways!

**Comment by div72** [comment]
> I didn't know about that element. Would you like me to rewrite this PR with that element?

That'd be better unless there's an argument for sliders that makes them better than ranges.

> But also, this PR did not include any server-side logic to bound the inputs to the schema min-max. So as written, anybody could POST whatever they want anyways!

Don't worry about that, radio buttons don't have input validation either. I'll add that later.

**Comment by div72** [comment]
Uhh, I've had a brain fart and my previous comment does not actually make sense. The range input type is already a slider, I was thinking about type="range" vs type="number", the latter which already shows the numerical value without having to use any JS. I can do the change if you don't want to, sorry for making you waste effort for twice.

**Comment by bgstack15** [comment]
Hm, at this point yes, please make any changes that you wish to implement. If you could get this to show a slider and a number all at once, that would be awesome! The less javascript the better, in my opinion.

**Comment by div72** [comment]
Thank you for your contribution.

**Pull request merged**
